### ISSUE TITLE
Atomic tablebase segfault

### ISSUE THREAD

**Issue by niklasf** [ddugovic/Stockfish#123]
To exclude hardware errors, here's the checksums of my tables to `md5sum -c`: https://gist.github.com/niklasf/456b0db4d80a2d49af79e114bec44dbf

FEN: 6QQ/8/8/4k3/4K3/8/8/8 w - - 0 1

```
gdb ./stockfish 
GNU gdb (Debian 7.11.1-2) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./stockfish...done.
(gdb) run
Starting program: /home/niklas/Projekte/Stockfish/src/stockfish 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Stockfish 151116 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
[New Thread 0x7ffff6b76700 (LWP 497)]
setoption name UCI_Variant value atomic
setoption name SyzygyPath value /home/niklas/Projekte/tbserve/src/atomic/
info string Found 145 tablebases
position fen 6QQ/8/8/4k3/4K3/8/8/8 w - - 0 1
info string variant atomic startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
d

 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   | Q | Q |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | k |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | K |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+

Fen: 6QQ/8/8/4k3/4K3/8/8/8 w - - 0 1
Key: 136B1EC8E57C38E7

Thread 1 "stockfish" received signal SIGSEGV, Segmentation fault.
0x000000000045018b in (anonymous namespace)::decompress_pairs (d=d@entry=0xa058d0, idx=idx@entry=28)
    at syzygy/tbprobe.cpp:555
555	        offset += d->blockLength[--block] + 1;
(gdb) backtrace
#0  0x000000000045018b in (anonymous namespace)::decompress_pairs (d=d@entry=0xa058d0, idx=idx@entry=28) at syzygy/tbprobe.cpp:555
#1  0x000000000045b064 in (anonymous namespace)::decompress_pairs (idx=28, d=0xa058d0) at /usr/include/c++/6/bits/basic_ios.h:282
#2  (anonymous namespace)::do_probe_table<(anonymous namespace)::DTZEntry> (result=0x7fffffffbdf0, wdl=Tablebases::WDLWin, entry=0xa0e6a0, pos=...)
    at syzygy/tbprobe.cpp:888
#3  (anonymous namespace)::probe_table<(anonymous namespace)::DTZEntry> (wdl=<optimized out>, result=0x7fffffffbdf0, pos=...)
    at syzygy/tbprobe.cpp:1238
#4  Tablebases::probe_dtz (pos=..., result=result@entry=0x7fffffffbe70) at syzygy/tbprobe.cpp:1502
#5  0x000000000042e486 in operator<< (os=..., pos=...) at position.cpp:154
#6  0x000000000044a635 in UCI::loop (argc=argc@entry=1, argv=argv@entry=0x7fffffffde38) at uci.cpp:238
#7  0x00000000004051b2 in main (argc=1, argv=0x7fffffffde38) at main.cpp:50

**Comment by ianfab** [comment]
I have just tested a few positions with KQQvK, and this segfault seems to always occur when kings are connected. However, I can not reproduce the segfault with other material configurations. (My checksums agree, at least for 3 and 4 men, since I haven't generated 5 men atomic TB.)
