### ISSUE TITLE
Horde analysis segfaults

### ISSUE THREAD

**Issue by ornicar** [ddugovic/Stockfish#47]
https://gist.github.com/ornicar/c5045e5958306668583b9760311e4216

Using fishnet's `stockfish-x86_64-modern` on 64bits Debian 8

**Comment by ornicar** [comment]
I don't know if it's relevant, but when I use local stockfish on the same game, then starting from this move https://en.lichess.org/X0mIbJG7#71 SF always suggests a move for white, even when it's black turn to move.

**Comment by niklasf** [comment]
Does not occur in git master. Still it would be great if we could pin down the problem.

Minimal example:

```
setoption name UCI_Horde value true
position fen pppppppp/pppppppp/pppppppp/pppppppp/1pp2pp1/8/PPPPPPPP/RNBQKBNR w KQ - 0 1
go nodes 5000
```

gdb:

```
Starting program: /home/niklas/Projekte/fishnet/stockfish-x86_64-bmi2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Stockfish 130816 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
[New Thread 0x7ffff6f7b700 (LWP 32764)]
setoption name UCI_Horde value true
position fen pppppppp/pppppppp/pppppppp/pppppppp/1pp2pp1/8/PPPPPPPP/RNBQKBNR w KQ - 0 1
go nodes 5000
info depth 1 seldepth 1 multipv 1 score cp 1310 nodes 24 nps 6000 tbhits 0 time 4 pv d2d3
info depth 2 seldepth 2 multipv 1 score cp 1317 nodes 93 nps 23250 tbhits 0 time 4 pv d2d3 c4d3
info depth 3 seldepth 3 multipv 1 score cp 1317 nodes 174 nps 43500 tbhits 0 time 4 pv d2d3 c4d3 e2d3
info depth 4 seldepth 4 multipv 1 score cp 1292 nodes 1495 nps 299000 tbhits 0 time 5 pv a2a3 d5d4 e2e3 c4c3
info depth 5 seldepth 5 multipv 1 score cp 1273 nodes 3667 nps 523857 tbhits 0 time 7 pv e2e3 d5d4 g1e2 d4d3 c2d3 c4d3
info depth 6 seldepth 6 multipv 1 score cp 1273 nodes 4559 nps 569875 tbhits 0 time 8 pv e2e3 d5d4 g1e2 d4d3 c2d3 c4d3

Thread 2 "stockfish-x86_6" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6f7b700 (LWP 32764)]
0x0000000000415113 in Position::attackers_to(Square, unsigned long) const ()
(gdb) backtrace
#0  0x0000000000415113 in Position::attackers_to(Square, unsigned long) const ()
#1  0x0000000000419c01 in MovePicker::next_move() ()
#2  0x000000000042500e in Value (anonymous namespace)::qsearch<((anonymous namespace)::NodeType)0, false>(Position&, Search::Stack*, Value, Value, Depth) [clone .22917] ()
#3  0x000000000041c609 in Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool) [clone .22995] ()
#4  0x000000000041bde1 in Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool) [clone .22995] ()
#5  0x000000000041bde1 in Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool) [clone .22995] ()
#6  0x000000000041bde1 in Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool) [clone .22995] ()
#7  0x000000000041daae in Value (anonymous namespace)::search<((anonymous namespace)::NodeType)1>(Position&, Search::Stack*, Value, Value, Depth, bool) [clone .23579] ()
#8  0x000000000041de07 in Value (anonymous namespace)::search<((anonymous namespace)::NodeType)1>(Position&, Search::Stack*, Value, Value, Depth, bool) [clone .23579] ()
#9  0x000000000041de07 in Value (anonymous namespace)::search<((anonymous namespace)::NodeType)1>(Position&, Search::Stack*, Value, Value, Depth, bool) [clone .23579] ()
#10 0x0000000000433e39 in Thread::search() ()
#11 0x0000000000430fc2 in MainThread::search() ()
#12 0x000000000042ef65 in Thread::idle_loop() ()
#13 0x00007ffff78f0740 in std::execute_native_thread_routine_compat (
    __p=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:110
#14 0x00007ffff7bc4454 in start_thread () from /usr/lib/libpthread.so.0
#15 0x00007ffff70647df in clone () from /usr/lib/libc.so.6
```

**Comment by ornicar** [comment]
https://en.lichess.org/X0mIbJG7#71 suggests that it's ply 71 that breaks SF.

**Comment by ddugovic** [comment]
Is the log accurate?  Are we really sending the moves e2e3 d5d4 d2d3 d6d5 h2h3 g4g3 f2g3 f4g3 g1e2 h5h4 e3d4 **$5d4** to Stockfish?

**Comment by ornicar** [comment]
no that would be my copy-pasta from the server tmux.

**Comment by ddugovic** [comment]
On 64-bit Ubuntu with latest SF code, the command `d` after that input produces this output:

```
 +---+---+---+---+---+---+---+---+
 | p |   |   |   |   | p | p | p |
 +---+---+---+---+---+---+---+---+
 | p |   | Q | p |   | p | p | p |
 +---+---+---+---+---+---+---+---+
 |   |   | p | p |   |   | p |   |
 +---+---+---+---+---+---+---+---+
 |   | p |   |   | p |   |   | p |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   | p | R |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   | p | p |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | B |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   | B |   | K |   |   |   |
 +---+---+---+---+---+---+---+---+

Fen: p4ppp/p1Qp1ppp/2pp2p1/1p2p2p/6pR/5pp1/4B3/2B1K3 w - - 0 36
Key: A2CDA313BAB57788
Checkers: 
```

**Comment by ddugovic** [comment]
Compiling with `make build ARCH=x86-64-modern debug=yes` I found the cause:

`stockfish: position.h:321: Square Position::square(Color) const [with PieceType Pt = (PieceType)6u]: Assertion `pieceCount[make_piece(c, Pt)] == 0' failed.`

**Comment by niklasf** [comment]
Git bisect says this commit fixed the issue: b70e32750e14d5041120b

**Comment by ddugovic** [comment]
Now I understand.  By enforcing that the first step of position setup is to set the variant (to address position setup errors for other variants) position setup also enforces Horde position rules.

Horde position rules are currently defined that White is the horde.  I'll assess what it takes to rewrite the code to handle either color being the horde.

**Comment by niklasf** [comment]
Ah ... so this was because it's a super old game?

**Comment by ddugovic** [comment]
I don't recall when the rules were changed, but [here's the game](https://en.lichess.org/X0mIbJG7#71).

**Comment by ornicar** [comment]
aaaaaah of course. The rules changed.


It's lila responsibility to refuse to analyse old horde games, I'll do that.

**Comment by ornicar** [comment]
fixed in lila: https://github.com/ornicar/lila/commit/40f62f658fe07ff45f8b164e3495811a345b704b
