### ISSUE TITLE
Horde segfault with current master (999f9a3180c75)

### ISSUE THREAD

**Issue by niklasf** [ddugovic/Stockfish#48]
```
><> 1: Analysing horde game https://en.lichess.org/vM3Qb7XO#97
><> 1: WARNING: Unexpected engine output: Segmentation fault
><> 1: DEBUG: HTTP response: 204 No Content
><> 1: DEBUG: No job found. Backing off 1.0s
><> 1: DEBUG: HTTP request: POST https://en.lichess.org/fishnet/acquire, body: {"fishnet": {"python": "2.7.12", "apikey": "********", "version": "1.9.1"}, "stockfish": {"name": "Stockfish 040916 64 BMI2", "options": {"hash": "256", "threads": "7"}}}
><> 1: DEBUG: HTTP response: 204 No Content
><> 1: DEBUG: No job found. Backing off 1.5s
><> 1: DEBUG: HTTP request: POST https://en.lichess.org/fishnet/acquire, body: {"fishnet": {"python": "2.7.12", "apikey": "********", "version": "1.9.1"}, "stockfish": {"name": "Stockfish 040916 64 BMI2", "options": {"hash": "256", "threads": "7"}}}
><> 1: DEBUG: HTTP response: 204 No Content
><> 1: DEBUG: No job found. Backing off 3.9s
><> 1: DEBUG: HTTP request: POST https://en.lichess.org/fishnet/acquire, body: {"fishnet": {"python": "2.7.12", "apikey": "********", "version": "1.9.1"}, "stockfish": {"name": "Stockfish 040916 64 BMI2", "options": {"hash": "256", "threads": "7"}}}
><> 1: DEBUG: HTTP response: 204 No Content
><> 1: DEBUG: No job found. Backing off 2.5s
><> 1: DEBUG: HTTP request: POST https://en.lichess.org/fishnet/acquire, body: {"fishnet": {"python": "2.7.12", "apikey": "********", "version": "1.9.1"}, "stockfish": {"name": "Stockfish 040916 64 BMI2", "options": {"hash": "256", "threads": "7"}}}
><> 1: DEBUG: HTTP response: 202 Accepted
><> 1: DEBUG: Got job: {"work":{"type":"analysis","id":"QoxPvENH"},"nodes":3500000,"game_id":"vM3Qb7XO","position":"rnbqkbnr/pppppppp/8/1PP2PP1/PPPPPPPP/PPPPPPPP/PPPPPPPP/PPPPPPPP w kq - 0 1","variant":"horde","moves":"a4a5 a7a6 b5b6 c7b6 a5b6 d7d6 c5c6 h7h6 c6c7 d8d7 c7b8q a8b8 g5g6 f7g6 f5g6 e7e6 e4e5 d6e5 f4e5 g8e7 f3f4 e7g6 f4f5 e6f5 h4h5 f5g4 h5g6 g4h3 g2h3 h6h5 c4c5 f8e7 d4d5 d7d8 d5d6 e7f6 e5f6 d8f6 c5c6 b7c6 c3c4 c8d7 c4c5 f6g6 d3d4 h5h4 g3g4 d7g4 h3g4 g6g4 g1g2 g4d7 h2h3 h8h6 e3e4 h6g6 e4e5 d7e6 e2e4 g6g2 h1g2 g7g5 f2f4 g5f4 f1f3 e6f7 d4d5 c6d5 c5c6 b8b6 c6c7 f7d7 e4d5 b6d6 e5e6 d6e6 d5e6 d7c8 d2d4 e8e7 d4d5 e7d6 e6e7 d6d5 e7e8q c8e8 c7c8q e8c8 c2c4 d5d6 c4c5 d6d7 d1d2 d7e7 d2d3 c8c6 d3d4"}
><> 1: ENGINE: 11523 << setoption name UCI_Chess960 value false
><> 1: ENGINE: 11523 << setoption name UCI_Atomic value false
><> 1: ENGINE: 11523 << setoption name UCI_Horde value true
><> 1: ENGINE: 11523 << setoption name UCI_House value false
><> 1: ENGINE: 11523 << setoption name UCI_KingOfTheHill value false
><> 1: ENGINE: 11523 << setoption name UCI_Race value false
><> 1: ENGINE: 11523 << setoption name UCI_3Check value false
><> 1: ENGINE: 11523 << setoption name Skill Level value 20
><> 1: ENGINE: 11523 << isready
><> 1: ENGINE: 11523 >> readyok
><> 1: ENGINE: 11523 << ucinewgame
><> 1: ENGINE: 11523 << isready
><> 1: ENGINE: 11523 >> readyok
><> 1: ENGINE: 11523 << position fen rnbqkbnr/pppppppp/8/1PP2PP1/PPPPPPPP/PPPPPPPP/PPPPPPPP/PPPPPPPP w kq - 0 1 moves a4a5 a7a6 b5b6 c7b6 a5b6 d7d6 c5c6 h7h6 c6c7 d8d7 c7b8q a8b8 g5g6 f7g6 f5g6 e7e6 e4e5 d6e5 f4e5 g8e7 f3f4 e7g6 f4f5 e6f5 h4h5 f5g4 h5g6 g4h3 g2h3 h6h5 c4c5 f8e7 d4d5 d7d8 d5d6 e7f6 e5f6 d8f6 c5c6 b7c6 c3c4 c8d7 c4c5 f6g6 d3d4 h5h4 g3g4 d7g4 h3g4 g6g4 g1g2 g4d7 h2h3 h8h6 e3e4 h6g6 e4e5 d7e6 e2e4 g6g2 h1g2 g7g5 f2f4 g5f4 f1f3 e6f7 d4d5 c6d5 c5c6 b8b6 c6c7 f7d7 e4d5 b6d6 e5e6 d6e6 d5e6 d7c8 d2d4 e8e7 d4d5 e7d6 e6e7 d6d5 e7e8q c8e8 c7c8q e8c8 c2c4 d5d6 c4c5 d6d7 d1d2 d7e7 d2d3 c8c6 d3d4
><> 1: ENGINE: 11523 << isready
><> 1: ENGINE: 11523 >> readyok
><> 1: ENGINE: 11523 << go movetime 4000 nodes 3500000
><> 1: ENGINE: 11523 >> info depth 1 seldepth 1 multipv 1 score cp 188 nodes 245 nps 245000 tbhits 0 time 1 pv c6g6
><> 1: ENGINE: 11523 >> info depth 2 seldepth 2 multipv 1 score cp 228 nodes 587 nps 587000 tbhits 0 time 1 pv c6d5 c1c2
><> 1: ENGINE: 11523 >> info depth 3 seldepth 3 multipv 1 score cp 334 nodes 862 nps 862000 tbhits 0 time 1 pv c6g6 a3a4 g6g2
><> 1: ENGINE: 11523 >> Segmentation fault
><> 1: ERROR: Engine process has died. Backing off 0.9s
Traceback (most recent call last):
  File "./fishnet.py", line 625, in run_inner
    path, request = self.work()
  File "./fishnet.py", line 728, in work
    result = self.analysis(self.job)
  File "./fishnet.py", line 811, in analysis
    nodes=nodes, movetime=4000)
  File "./fishnet.py", line 487, in go
    command, arg = recv_uci(p)
  File "./fishnet.py", line 409, in recv_uci
    command_and_args = recv(p).split(None, 1)
  File "./fishnet.py", line 398, in recv
    raise EOFError()
EOFError
><> 1: Aborted job QoxPvENH
```

**Comment by niklasf** [comment]
Condensed example:

```
setoption name UCI_Horde value true
position fen rnbqkbnr/pppppppp/8/1PP2PP1/PPPPPPPP/PPPPPPPP/PPPPPPPP/PPPPPPPP w kq - 0 1 moves a4a5 a7a6 b5b6 c7b6 a5b6 d7d6 c5c6 h7h6 c6c7 d8d7 c7b8q a8b8 g5g6 f7g6 f5g6 e7e6 e4e5 d6e5 f4e5 g8e7 f3f4 e7g6 f4f5 e6f5 h4h5 f5g4 h5g6 g4h3 g2h3 h6h5 c4c5 f8e7 d4d5 d7d8 d5d6 e7f6 e5f6 d8f6 c5c6 b7c6 c3c4 c8d7 c4c5 f6g6 d3d4 h5h4 g3g4 d7g4 h3g4 g6g4 g1g2 g4d7 h2h3 h8h6 e3e4 h6g6 e4e5 d7e6 e2e4 g6g2 h1g2 g7g5 f2f4 g5f4 f1f3 e6f7 d4d5 c6d5 c5c6 b8b6 c6c7 f7d7 e4d5 b6d6 e5e6 d6e6 d5e6 d7c8 d2d4 e8e7 d4d5 e7d6 e6e7 d6d5 e7e8q c8e8 c7c8q e8c8 c2c4 d5d6 c4c5 d6d7 d1d2 d7e7 d2d3 c8c6 d3d4
go movetime 4000 nodes 3500000
```

**Comment by niklasf** [comment]
Backtrace:

```
(gdb) run
Starting program: /home/niklas/Projekte/Stockfish/src/stockfish 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Stockfish 040916 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
[New Thread 0x7ffff6f7e700 (LWP 12969)]
setoption name UCI_Horde value true
position fen rnbqkbnr/pppppppp/8/1PP2PP1/PPPPPPPP/PPPPPPPP/PPPPPPPP/PPPPPPPP w kq - 0 1
go movetime 4000 nodes 3500000
info depth 1 seldepth 1 multipv 1 score cp -60 nodes 12 nps 6000 tbhits 0 time 2 pv a4a5
info depth 2 seldepth 2 multipv 1 score cp -94 nodes 100 nps 50000 tbhits 0 time 2 pv h4h5 c7c6
info depth 3 seldepth 3 multipv 1 score cp -94 nodes 258 nps 86000 tbhits 0 time 3 pv h4h5 c7c6 a4a5
info depth 4 seldepth 4 multipv 1 score cp -49 nodes 624 nps 208000 tbhits 0 time 3 pv a4a5 e7e6 d4d5 e6d5
info depth 5 seldepth 5 multipv 1 score cp -72 nodes 2173 nps 362166 tbhits 0 time 6 pv a4a5 d7d6 d4d5 h7h6 c5c6
info depth 6 seldepth 6 multipv 1 score cp -77 nodes 4379 nps 486555 tbhits 0 time 9 pv e4e5 e7e6 h4h5 h7h6 g5g6 f7g6
info depth 7 seldepth 7 multipv 1 score cp -60 nodes 8930 nps 637857 tbhits 0 time 14 pv e4e5 h7h6 d4d5 a7a5 b4a5 h6g5 f4g5
info depth 8 seldepth 8 multipv 1 score cp -67 nodes 13873 nps 770722 tbhits 0 time 18 pv e4e5 h7h6 d4d5 a7a6 d3d4 h6g5 f4g5 a6b5
info depth 9 seldepth 12 multipv 1 score cp -54 nodes 38529 nps 963225 tbhits 0 time 40 pv e4e5 d7d6 a4a5 d6e5 f4e5 e7e6 f5e6 f7e6 f3f4
info depth 10 seldepth 12 multipv 1 score cp -58 nodes 75294 nps 1060478 tbhits 0 time 71 pv d4d5 h7h6 e4e5 a7a6 d3d4 d7d6 b5a6 b8a6 g5g6 f7g6 f5g6

Thread 2 "stockfish" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6f7e700 (LWP 12969)]
Position::attackers_to (this=this@entry=0xbc2ad8, s=SQ_NONE, occupied=<optimized out>) at position.cpp:600
600	        | (attacks_bb<ROOK  >(s, occupied) & pieces(ROOK,   QUEEN))
(gdb) backtrace
#0  Position::attackers_to (this=this@entry=0xbc2ad8, s=SQ_NONE, occupied=<optimized out>) at position.cpp:600
#1  0x000000000042d193 in Position::attackers_to (s=<optimized out>, this=0xbc2ad8) at position.h:402
#2  Position::do_move (this=this@entry=0xbc2ad8, m=m@entry=(MOVE_NULL | unknown: 53054), newSt=..., givesCheck=givesCheck@entry=true) at position.cpp:1233
#3  0x0000000000430684 in (anonymous namespace)::qsearch<(<unnamed>::NodeType)0u, false>(Position &, Search::Stack *, Value, Value, Depth) (pos=..., ss=0x7ffff6f7c7b0, alpha=128, beta=129, 
    depth=<optimized out>) at search.cpp:1641
#4  0x0000000000432e11 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c780, alpha=alpha@entry=-129, 
    beta=beta@entry=-128, depth=depth@entry=ONE_PLY, cutNode=cutNode@entry=true) at search.cpp:1237
#5  0x0000000000432545 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c750, alpha=alpha@entry=128, beta=129, 
    depth=depth@entry=3, cutNode=<optimized out>) at search.cpp:1226
#6  0x0000000000432596 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c720, alpha=alpha@entry=-129, beta=-128, 
    depth=depth@entry=4, cutNode=<optimized out>) at search.cpp:1238
#7  0x0000000000432596 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c6f0, alpha=alpha@entry=128, beta=129, 
    depth=depth@entry=5, cutNode=<optimized out>) at search.cpp:1238
#8  0x0000000000432596 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c6c0, alpha=alpha@entry=-129, beta=-128, 
    depth=depth@entry=6, cutNode=<optimized out>) at search.cpp:1238
#9  0x0000000000432596 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c690, alpha=alpha@entry=128, beta=129, 
    depth=depth@entry=7, cutNode=<optimized out>) at search.cpp:1238
#10 0x0000000000432596 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c660, alpha=alpha@entry=-129, beta=-128, 
    depth=depth@entry=8, cutNode=<optimized out>) at search.cpp:1238
#11 0x0000000000432596 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c630, alpha=alpha@entry=128, beta=129, 
    depth=depth@entry=8, cutNode=<optimized out>) at search.cpp:1238
#12 0x0000000000432596 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c600, alpha=alpha@entry=-129, 
    beta=beta@entry=-128, depth=depth@entry=9, cutNode=cutNode@entry=true) at search.cpp:1238
#13 0x000000000043542f in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=ss@entry=0x7ffff6f7c5d0, alpha=alpha@entry=128, beta=164, 
    depth=depth@entry=10, cutNode=cutNode@entry=false) at search.cpp:1238
#14 0x0000000000435479 in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., ss=0x7ffff6f7c5a0, alpha=alpha@entry=-164, 
    beta=beta@entry=-128, depth=<optimized out>, cutNode=cutNode@entry=false) at search.cpp:1251
#15 0x0000000000438055 in Thread::search (this=this@entry=0xbc29c0) at search.cpp:430
#16 0x000000000043ad28 in MainThread::search (this=0xbc29c0) at search.cpp:298
#17 0x000000000043dacd in Thread::idle_loop (this=0xbc29c0) at thread.cpp:113
#18 0x00007ffff78f498f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007ffff7bc3464 in start_thread (arg=0x7ffff6f7e700) at pthread_create.c:333
#20 0x00007ffff706630d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by niklasf** [comment]
Older versions (HEAD~1) seem to survive if not build for debugging. Otherwise:

```
Stockfish 040916 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name UCI_Horde value true
position fen rnbqkbnr/pppppppp/8/1PP2PP1/PPPPPPPP/PPPPPPPP/PPPPPPPP/PPPPPPPP w kq - 0 1
go movetime 4000 nodes 3500000
info depth 1 seldepth 1 multipv 1 score cp 63 nodes 12 nps 6000 tbhits 0 time 2 pv a4a5
info depth 2 seldepth 2 multipv 1 score cp 53 nodes 50 nps 25000 tbhits 0 time 2 pv d4d5 a7a6
info depth 3 seldepth 3 multipv 1 score cp 53 nodes 186 nps 93000 tbhits 0 time 2 pv d4d5 a7a6 b5a6
info depth 4 seldepth 4 multipv 1 score cp 52 nodes 741 nps 247000 tbhits 0 time 3 pv d4d5 h7h6 g5g6 f7g6
info depth 5 seldepth 5 multipv 1 score cp 52 nodes 1123 nps 280750 tbhits 0 time 4 pv d4d5 h7h6 g5g6 f7g6 f5g6
info depth 6 seldepth 6 multipv 1 score cp 29 nodes 4312 nps 539000 tbhits 0 time 8 pv e4e5 d7d6 h4h5 d6e5 d4e5 h7h6
info depth 7 seldepth 7 multipv 1 score cp 48 nodes 11557 nps 679823 tbhits 0 time 17 pv d4d5 h7h6 g5h6 g8h6 g4g5 h6f5 e4f5
info depth 8 seldepth 8 multipv 1 score cp 42 nodes 24241 nps 932346 tbhits 0 time 26 pv d4d5 e7e6 h4h5 f7f6 h3h4 a7a6 b5a6 b8a6
info depth 9 seldepth 11 multipv 1 score cp 56 nodes 61044 nps 1090071 tbhits 0 time 56 pv d4d5 e7e6 e4e5 g8e7 d5d6 c7d6 e5d6 e7f5 g4f5
info depth 10 seldepth 12 multipv 1 score cp 63 nodes 106461 nps 1157184 tbhits 0 time 92 pv d4d5 h7h5 e4e5 a7a6 g4h5 h8h5 e3e4 h5h8 a4a5 a6b5
info depth 11 seldepth 14 multipv 1 score cp 67 nodes 218438 nps 1234112 tbhits 0 time 177 pv d4d5 d7d6 h4h5 a7a6 c5c6 b7c6 b5c6 b8c6 d5c6 e7e5 f5e6
info depth 12 seldepth 14 multipv 1 score cp 70 nodes 258973 nps 1239105 tbhits 0 time 209 pv d4d5 d7d6 h4h5 h7h6 g5g6 g8f6 c5c6 b8c6 b5c6 b7c6 g6f7 e8f7 d5c6
info depth 13 seldepth 18 multipv 1 score cp 72 nodes 622362 nps 1275331 tbhits 0 time 488 pv d4d5 e7e6 e4e5 d7d6 c5d6 c7d6 e3e4 a7a6 d5e6 f7e6 f5e6 c8e6 f4f5
info depth 14 seldepth 19 multipv 1 score cp 87 nodes 1080851 nps 1294432 tbhits 0 time 835 pv d4d5 d7d6 a4a5 a7a6 d3d4 h7h6 c5c6 a6b5 c4b5 b7c6 d5c6 h6g5 h4g5 b8c6 b5c6 e7e6 d4d5
info depth 15 seldepth 21 multipv 1 score cp 81 nodes 1494873 nps 1297632 hashfull 559 tbhits 0 time 1152 pv d4d5 d7d6 a4a5 a7a6 d3d4 a6b5 c4b5 e7e6 d5e6 f7e6 c5d6 c7d6 c3c4 e6f5 g4f5 b8d7 h4h5 g8e7
info depth 16 seldepth 22 multipv 1 score cp 87 nodes 2138330 nps 1295957 hashfull 723 tbhits 0 time 1650 pv d4d5 d7d6 a4a5 a7a6 d3d4 b8d7 c5c6 a6b5 c4b5 b7b6 c6d7 d8d7 a5b6 c7b6 c3c4 h7h5 e4e5 h5g4 e5e6
stockfish: position.h:321: Square Position::square(Color) const [with PieceType Pt = (PieceType)3u]: Assertion `pieceCount[c][Pt] == 0' failed.
[1]    13853 abort      ./stockfish
```

That's all from me for today ;)

**Comment by ddugovic** [comment]
Thanks @niklasf !

```
Thread 2 "stockfish" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6f4f700 (LWP 9954)]
0x000000000042aa28 in Position::gives_check (this=this@entry=0xbc4ad8, m=m@entry=(MOVE_NULL | unknown: 34710)) at position.cpp:931
931                 | (attacks_bb<BISHOP>(square<KING>(~sideToMove), b) & pieces(sideToMove, QUEEN, BISHOP));
(gdb) bt
#0  0x000000000042aa28 in Position::gives_check (this=this@entry=0xbc4ad8, m=m@entry=(MOVE_NULL | unknown: 34710)) at position.cpp:931
#1  0x0000000000433b24 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=ss@entry=0x7ffff6f4d5c0, alpha=alpha@entry=651, beta=beta@entry=652, depth=depth@entry=2, cutNode=cutNode@entry=true) at search.cpp:1031
#2  0x0000000000436cba in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=ss@entry=0x7ffff6f4d590, alpha=alpha@entry=-652, beta=-616, depth=depth@entry=4, cutNode=cutNode@entry=false) at search.cpp:1226
#3  0x00000000004375fd in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=0x7ffff6f4d560, alpha=alpha@entry=616, beta=beta@entry=652, depth=<optimized out>, cutNode=cutNode@entry=false) at search.cpp:1248
#4  0x00000000004396b5 in Thread::search (this=this@entry=0xbc49c0) at search.cpp:430
#5  0x000000000043bd48 in MainThread::search (this=0xbc49c0) at search.cpp:298
#6  0x000000000043ec31 in Thread::idle_loop (this=0xbc49c0) at thread.cpp:113
#7  0x00007ffff78f0c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7bc16fa in start_thread (arg=0x7ffff6f4f700) at pthread_create.c:333
#9  0x00007ffff7056b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
