### ISSUE TITLE
Atomic chess segfault

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#49]
Input:
```
setoption name UCI_Chess960 value false
setoption name UCI_Atomic value true
setoption name UCI_Horde value false
setoption name UCI_House value false
setoption name UCI_KingOfTheHill value false
setoption name UCI_Race value false
setoption name UCI_3Check value false
setoption name Skill Level value 14
isready
position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves
isready
go movetime 400 depth 8
```

GDB:
```
info depth 1 seldepth 1 multipv 1 score cp 81 nodes 74 nps 24666 tbhits 0 time 3 pv e2e3
info depth 2 seldepth 2 multipv 1 score cp 84 nodes 172 nps 43000 tbhits 0 time 4 pv e2e3 b7b6
info depth 3 seldepth 3 multipv 1 score cp 104 nodes 452 nps 75333 tbhits 0 time 6 pv d2d4 d7d6 e2e4

Thread 2 "stockfish" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6f4f700 (LWP 31729)]
0x000000000042a67a in Position::key_after (this=this@entry=0xbc2ad8, m=m@entry=(MOVE_NULL | unknown: 2714)) at position.cpp:1430
1430                  k ^= Zobrist::psq[bpc][bsq];
(gdb) bt
#0  0x000000000042a67a in Position::key_after (this=this@entry=0xbc2ad8, m=m@entry=(MOVE_NULL | unknown: 2714)) at position.cpp:1430
#1  0x00000000004320e1 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=0x7ffff6f4d5e0, alpha=alpha@entry=-76, beta=beta@entry=-75, depth=depth@entry=ONE_PLY, cutNode=<optimized out>) at search.cpp:1162
#2  0x0000000000432759 in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=ss@entry=0x7ffff6f4d5b0, alpha=alpha@entry=75, beta=beta@entry=76, depth=depth@entry=2, cutNode=cutNode@entry=true) at search.cpp:1235
#3  0x00000000004352da in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=ss@entry=0x7ffff6f4d580, alpha=-76, alpha@entry=-32001, beta=31997, depth=depth@entry=3, cutNode=cutNode@entry=false) at search.cpp:1226
#4  0x0000000000435c1d in (anonymous namespace)::search<(<unnamed>::NodeType)1u>(Position &, Search::Stack *, Value, Value, Depth, bool) (pos=..., 
    ss=0x7ffff6f4d550, alpha=alpha@entry=-32001, beta=beta@entry=VALUE_INFINITE, depth=<optimized out>, cutNode=cutNode@entry=false)
    at search.cpp:1248
#5  0x0000000000437cd5 in Thread::search (this=this@entry=0xbc29c0) at search.cpp:430
#6  0x000000000043a2d8 in MainThread::search (this=0xbc29c0) at search.cpp:298
#7  0x000000000043d251 in Thread::idle_loop (this=0xbc29c0) at thread.cpp:113
#8  0x00007ffff78f0c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7bc16fa in start_thread (arg=0x7ffff6f4f700) at pthread_create.c:333
#10 0x00007ffff7056b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by ornicar** [comment]
lichess logs confirm that mostly, if not only, atomic games are affected indeed.
