### ISSUE TITLE
Switching variants -> may crash after some searching

### ISSUE THREAD

**Issue by Vempele** [ddugovic/Stockfish#512]
uci
setoption name UCI_Variant value crazyhouse
position startpos
go depth 20
setoption name UCI_Variant value giveaway
position startpos
go depth 20
<crash after posting a depth 17 score>

At least Stockfish 9 64 BMI2 as well as 2018-03-17 64 BMI2.

**Comment by ianfab** [comment]
Thanks for the report, the issue is reproducible. With gdb I found the origin of the segfault (see below), although it looks quite confusing. The context of crazyhouse, giveaway, and continuation history suggests that it has to do with the move encoding in these variants.

```
Thread 2 "stockfish" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5f4d700 (LWP 3733)]
0x000000000046a18a in StatsEntry<short, 32, 936>::operator<< (bonus=1, this=0x9342f3a)
    at movepick.h:54
54	    entry += bonus * W - entry * abs(bonus) / D;
(gdb) bt
#0  0x000000000046a18a in StatsEntry<short, 32, 936>::operator<< (bonus=1, this=0x9342f3a)
    at movepick.h:54
#1  (anonymous namespace)::update_continuation_histories (ss=0x7ffff5f4b9b0, pc=1129735, to=SQ_F3, 
    bonus=1) at search.cpp:1769
#2  0x000000000046abba in (anonymous namespace)::update_quiet_stats (pos=..., 
    ss=ss@entry=0x7ffff5f4b9b0, move=move@entry=(MOVE_NULL | unknown: 37140), 
    quiets=quiets@entry=0x0, quietsCnt=quietsCnt@entry=0, bonus=1) at search.cpp:1807
#3  0x000000000046ce7f in (anonymous namespace)::search<(<unnamed>::NodeType)0u>(Position &, Search::Stack *, Value, Value, Depth, bool, bool) (pos=..., ss=ss@entry=0x7ffff5f4b9b0, 
    alpha=alpha@entry=145, beta=146, depth=depth@entry=ONE_PLY, cutNode=true, 
    skipEarlyPruning=false) at search.cpp:848
```

**Comment by ianfab** [comment]
The fix seems to be pretty simple. The issue was that for variants other than crazyhouse, the moved piece could not be determined correctly for drop moves. Of course drop moves only exist in crazyhouse, but since drop moves might still be in the histories or the transposition table, we still need to handle them properly, even after switching the variant.
